exclude: ^vendor
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
  - repo: local
    hooks:
      - id: lint-staged
        name: Lint Staged for Next
        entry: npx lint-staged --cwd ./client --config ./client/.lintstagedrc.yaml
        language: system
        types_or:
          - tsx
          - jsx
        verbose: true
